/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ArchiwumRouteImport } from './routes/archiwum'
import { Route as IndexRouteImport } from './routes/index'

const ArchiwumRoute = ArchiwumRouteImport.update({
  id: '/archiwum',
  path: '/archiwum',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archiwum': typeof ArchiwumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archiwum': typeof ArchiwumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archiwum': typeof ArchiwumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/archiwum'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/archiwum'
  id: '__root__' | '/' | '/archiwum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiwumRoute: typeof ArchiwumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/archiwum': {
      id: '/archiwum'
      path: '/archiwum'
      fullPath: '/archiwum'
      preLoaderRoute: typeof ArchiwumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiwumRoute: ArchiwumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
